const LABELS = {
  en: {
    any: 'Any',
    allCities: 'All cities',
    allSkills: 'All skills',
    searchByCity: 'Search by city and skill to see available matches',
    showMatching: 'Show matching workers',
    city: {
      kurnool: 'Kurnool',
      bhiwani: 'Bhiwani',
      delhi: 'Delhi',
      hyderabad: 'Hyderabad',
      mumbai: 'Mumbai',
      pune: 'Pune',
      bengaluru: 'Bengaluru',
      chennai: 'Chennai',
      kolkata: 'Kolkata',
      gurugram: 'Gurugram',
      noida: 'Noida',
      ghaziabad: 'Ghaziabad',
      faridabad: 'Faridabad',
      lucknow: 'Lucknow',
      kanpur: 'Kanpur',
      jaipur: 'Jaipur',
      ahmedabad: 'Ahmedabad',
      surat: 'Surat',
      vadodara: 'Vadodara',
      indore: 'Indore',
      bhopal: 'Bhopal',
      nagpur: 'Nagpur',
      nashik: 'Nashik',
      patna: 'Patna',
      ranchi: 'Ranchi',
      bhubaneswar: 'Bhubaneswar',
      chandigarh: 'Chandigarh',
      amritsar: 'Amritsar',
      ludhiana: 'Ludhiana',
      kochi: 'Kochi',
      thiruvananthapuram: 'Thiruvananthapuram',
      vijayawada: 'Vijayawada',
      visakhapatnam: 'Visakhapatnam',
      warangal: 'Warangal',
      tirupati: 'Tirupati',
      coimbatore: 'Coimbatore',
      madurai: 'Madurai',
      dehradun: 'Dehradun',
      guwahati: 'Guwahati',
    },
    skill: {
      cooking: 'Cooking',
      cleaning: 'Cleaning',
      babysitting: 'Babysitting',
      eldercare: 'Elder care',
      laundry: 'Laundry',
      utensils: 'Utensils / dishes',
      mopping: 'Mopping',
      sweeping: 'Sweeping',
      dusting: 'Dusting',
      bathroom_cleaning: 'Bathroom cleaning',
      deep_cleaning: 'Deep cleaning',
      kitchen_helper: 'Kitchen helper',
      cooking_assistant: 'Cooking assistant',
      nanny: 'Nanny / aya',
      patient_care: 'Patient care',
      ironing: 'Ironing',
      gardening: 'Gardening',
      pet_care: 'Pet care',
      live_in_help: 'Live-in help',
    },
    verification: {
      id: 'ID verified',
      police: 'Police verified',
    },
    experience: {
      '': 'Any experience',
      1: '1+ years',
      2: '2+ years',
      3: '3+ years',
      5: '5+ years',
      8: '8+ years',
    },
    salary: {
      '': 'Any salary',
      5000: 'Up to Rs 5,000',
      8000: 'Up to Rs 8,000',
      10000: 'Up to Rs 10,000',
      15000: 'Up to Rs 15,000',
      20000: 'Up to Rs 20,000',
    },
    sort: {
      yes: 'Highest trust first',
      no: 'Default order',
    },
  },
  hi: {
    any: 'कोई भी',
    allCities: 'सभी शहर',
    allSkills: 'सभी कौशल',
    searchByCity: 'शहर और कौशल द्वारा खोजें उपलब्ध मेल देखने के लिए',
    showMatching: 'मेल खाने वाले कर्मचारी दिखाएं',
    city: { kurnool: 'कुरनूल', bhiwani: 'भिवानी', delhi: 'दिल्ली', hyderabad: 'हैदराबाद', mumbai: 'मुंबई', pune: 'पुणे', bengaluru: 'बेंगलुरु', chennai: 'चेन्नई', kolkata: 'कोलकाता', gurugram: 'गुरुग्राम', noida: 'नोएडा', ghaziabad: 'गाजियाबाद', faridabad: 'फरीदाबाद', lucknow: 'लखनऊ', kanpur: 'कानपुर', jaipur: 'जयपुर', ahmedabad: 'अहमदाबाद', surat: 'सूरत', vadodara: 'वडोदरा', indore: 'इंदौर', bhopal: 'भोपाल', nagpur: 'नागपुर', nashik: 'नाशिक', patna: 'पटना', ranchi: 'रांची', bhubaneswar: 'भुवनेश्वर', chandigarh: 'चंडीगढ़', amritsar: 'अमृतसर', ludhiana: 'लुधियाना', kochi: 'कोच्चि', thiruvananthapuram: 'तिरुवनंतपुरम', vijayawada: 'विजयवाड़ा', visakhapatnam: 'विशाखापट्टनम', warangal: 'वरंगल', tirupati: 'तिरुपति', coimbatore: 'कोयंबटूर', madurai: 'मदुरै', dehradun: 'देहरादून', guwahati: 'गुवाहाटी' },
    skill: { cooking: 'खाना बनाना', cleaning: 'सफाई', babysitting: 'बच्चों की देखभाल', eldercare: 'बुजुर्गों की देखभाल', laundry: 'कपड़े धोना', utensils: 'बर्तन धोना', mopping: 'पोछा लगाना', sweeping: 'झाड़ू लगाना', dusting: 'धूल साफ करना', bathroom_cleaning: 'बाथरूम सफाई', deep_cleaning: 'गहरी सफाई', kitchen_helper: 'रसोई सहायक', cooking_assistant: 'खाना बनाने में मदद', nanny: 'नैनी / आया', patient_care: 'मरीज की देखभाल', ironing: 'कपड़े प्रेस करना', gardening: 'बागवानी', pet_care: 'पालतू जानवरों की देखभाल', live_in_help: 'घर में रहने वाली मदद' },
    verification: { id: 'आईडी सत्यापित', police: 'पुलिस सत्यापित' },
    experience: { '': 'कोई भी अनुभव', 1: '1+ साल', 2: '2+ साल', 3: '3+ साल', 5: '5+ साल', 8: '8+ साल' },
    salary: { '': 'कोई भी वेतन', 5000: 'Rs 5,000 तक', 8000: 'Rs 8,000 तक', 10000: 'Rs 10,000 तक', 15000: 'Rs 15,000 तक', 20000: 'Rs 20,000 तक' },
    sort: { yes: 'सबसे भरोसेमंद पहले', no: 'डिफॉल्ट क्रम' },
  },
  te: {
    any: 'ఏదైనా',
    allCities: 'అన్ని నగరాలు',
    allSkills: 'అన్ని నైపుణ్యాలు',
    searchByCity: 'చేసిన నిర్దిష్ట ఆలోచనలు చూడటానికి నగరం మరియు నైపుణ్యం ద్వారా శోధించండి',
    showMatching: 'సరిపోలే కార్మికులను చూపించండి',
    city: { kurnool: 'కర్నూలు', bhiwani: 'భివాని', delhi: 'ఢిల్లీ', hyderabad: 'హైదరాబాద్', mumbai: 'ముంబై', pune: 'పూణే', bengaluru: 'బెంగళూరు', chennai: 'చెన్నై', kolkata: 'కోల్కతా', gurugram: 'గురుగ్రామ్', noida: 'నోయిడా', ghaziabad: 'ఘజియాబాద్', faridabad: 'ఫరీదాబాద్', lucknow: 'లక్నో', kanpur: 'కాన్పూర్', jaipur: 'జైపూర్', ahmedabad: 'అహ్మదాబాద్', surat: 'సూరత్', vadodara: 'వడోదర', indore: 'ఇండోర్', bhopal: 'భోపాల్', nagpur: 'నాగ్‌పూర్', nashik: 'నాశిక్', patna: 'పాట్నా', ranchi: 'రాంచీ', bhubaneswar: 'భువనేశ్వర్', chandigarh: 'చండీగఢ్', amritsar: 'అమృత్‌సర్', ludhiana: 'లూధియానా', kochi: 'కొచ్చి', thiruvananthapuram: 'తిరువనంతపురం', vijayawada: 'విజయవాడ', visakhapatnam: 'విశాఖపట్నం', warangal: 'వరంగల్', tirupati: 'తిరుపతి', coimbatore: 'కోయంబత్తూరు', madurai: 'మదురై', dehradun: 'డెహ్రాడూన్', guwahati: 'గువాహటి' },
    skill: { cooking: 'వంట', cleaning: 'శుభ్రపరచడం', babysitting: 'పిల్లల సంరక్షణ', eldercare: 'వృద్ధుల సంరక్షణ', laundry: 'బట్టలు ఉతకడం', utensils: 'గిన్నెలు కడగడం', mopping: 'నేల తుడవడం', sweeping: 'చీపురు వేయడం', dusting: 'దుమ్ము శుభ్రం', bathroom_cleaning: 'బాత్రూమ్ శుభ్రం', deep_cleaning: 'డీప్ క్లీనింగ్', kitchen_helper: 'వంటగది సహాయం', cooking_assistant: 'వంట సహాయం', nanny: 'నానీ / ఆయా', patient_care: 'రోగి సంరక్షణ', ironing: 'ఇస్త్రీ', gardening: 'తోట పని', pet_care: 'పెంపుడు జంతువుల సంరక్షణ', live_in_help: 'ఇంట్లో ఉండే సహాయం' },
    verification: { id: 'ID ధృవీకరించబడింది', police: 'పోలీస్ ధృవీకరణ' },
    experience: { '': 'ఏ అనుభవమైనా', 1: '1+ సంవత్సరాలు', 2: '2+ సంవత్సరాలు', 3: '3+ సంవత్సరాలు', 5: '5+ సంవత్సరాలు', 8: '8+ సంవత్సరాలు' },
    salary: { '': 'ఏ జీతమైనా', 5000: 'Rs 5,000 వరకు', 8000: 'Rs 8,000 వరకు', 10000: 'Rs 10,000 వరకు', 15000: 'Rs 15,000 వరకు', 20000: 'Rs 20,000 వరకు' },
    sort: { yes: 'అత్యధిక నమ్మకం ముందు', no: 'డిఫాల్ట్ క్రమం' },
  },
  kn: {
    any: 'ಯಾವುದಾದರೂ',
    allCities: 'ಎಲ್ಲಾ ನಗರಗಳು',
    allSkills: 'ಎಲ್ಲಾ ಕೌಶಲ್ಯಗಳು',
    searchByCity: 'ಲಭ್ಯವಾದ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ನೋಡಲು ನಗರ ಮತ್ತು ಕೌಶಲ್ಯದ ಮೂಲಕ ಹುಡುಕಿ',
    showMatching: 'ಹೊಂದಾಣಿಕೆಯಾದ ಕೆಲಸಗಾರರನ್ನು ತೋರಿಸಿ',
    city: { kurnool: 'ಕುರ್ನೂಲ್', bhiwani: 'ಭಿವಾನಿ', delhi: 'ದೆಹಲಿ', hyderabad: 'ಹೈದರಾಬಾದ್', mumbai: 'ಮುಂಬೈ', pune: 'ಪುಣೆ', bengaluru: 'ಬೆಂಗಳೂರು', chennai: 'ಚೆನ್ನೈ', kolkata: 'ಕೊಲ್ಕತ್ತಾ', gurugram: 'ಗುರುಗ್ರಾಮ್', noida: 'ನೊಯ್ಡಾ', ghaziabad: 'ಘಾಜಿಯಾಬಾದ್', faridabad: 'ಫರೀದಾಬಾದ್', lucknow: 'ಲಖನೌ', kanpur: 'ಕಾನ್ಪುರ', jaipur: 'ಜೈಪುರ', ahmedabad: 'ಅಹಮದಾಬಾದ್', surat: 'ಸುರತ್', vadodara: 'ವಡೋದರಾ', indore: 'ಇಂದೋರ್', bhopal: 'ಭೋಪಾಲ್', nagpur: 'ನಾಗಪುರ', nashik: 'ನಾಶಿಕ್', patna: 'ಪಟ್ನಾ', ranchi: 'ರಾಂಚಿ', bhubaneswar: 'ಭುವನೇಶ್ವರ', chandigarh: 'ಚಂಡೀಗಢ', amritsar: 'ಅಮೃತಸರ', ludhiana: 'ಲುಧಿಯಾನಾ', kochi: 'ಕೊಚ್ಚಿ', thiruvananthapuram: 'ತಿರುವನಂತಪುರಂ', vijayawada: 'ವಿಜಯವಾಡ', visakhapatnam: 'ವಿಶಾಖಪಟ್ಟಣಂ', warangal: 'ವರಂಗಲ್', tirupati: 'ತಿರುಪತಿ', coimbatore: 'ಕೊಯಂಬತ್ತೂರು', madurai: 'ಮದುರೈ', dehradun: 'ಡೆಹ್ರಾಡೂನ್', guwahati: 'ಗುವಾಹಟಿ' },
    skill: { cooking: 'ಅಡುಗೆ', cleaning: 'ಸ್ವಚ್ಛತೆ', babysitting: 'ಮಕ್ಕಳ ಆರೈಕೆ', eldercare: 'ಹಿರಿಯರ ಆರೈಕೆ', laundry: 'ಬಟ್ಟೆ ತೊಳೆಯುವುದು', utensils: 'ಪಾತ್ರೆ ತೊಳೆಯುವುದು', mopping: 'ನೆಲ ಒರೆಸುವುದು', sweeping: 'ಜಾಡು ಹಾಕುವುದು', dusting: 'ಧೂಳು ಸ್ವಚ್ಛತೆ', bathroom_cleaning: 'ಬಾತ್‌ರೂಮ್ ಸ್ವಚ್ಛತೆ', deep_cleaning: 'ಆಳವಾದ ಸ್ವಚ್ಛತೆ', kitchen_helper: 'ಅಡುಗೆಮನೆ ಸಹಾಯ', cooking_assistant: 'ಅಡುಗೆ ಸಹಾಯಕ', nanny: 'ನಾನಿ / ಆಯಾ', patient_care: 'ರೋಗಿ ಆರೈಕೆ', ironing: 'ಇಸ್ತ್ರಿ', gardening: 'ತೋಟಗಾರಿಕೆ', pet_care: 'ಪೆಟ್ ಆರೈಕೆ', live_in_help: 'ಮನೆಯಲ್ಲಿ ವಾಸಿಸುವ ಸಹಾಯ' },
    verification: { id: 'ID ಪರಿಶೀಲಿಸಲಾಗಿದೆ', police: 'ಪೊಲೀಸ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ' },
    experience: { '': 'ಯಾವುದೇ ಅನುಭವ', 1: '1+ ವರ್ಷ', 2: '2+ ವರ್ಷ', 3: '3+ ವರ್ಷ', 5: '5+ ವರ್ಷ', 8: '8+ ವರ್ಷ' },
    salary: { '': 'ಯಾವುದೇ ಸಂಬಳ', 5000: 'Rs 5,000 ವರೆಗೆ', 8000: 'Rs 8,000 ವರೆಗೆ', 10000: 'Rs 10,000 ವರೆಗೆ', 15000: 'Rs 15,000 ವರೆಗೆ', 20000: 'Rs 20,000 ವರೆಗೆ' },
    sort: { yes: 'ಹೆಚ್ಚಿನ ವಿಶ್ವಾಸ ಮೊದಲು', no: 'ಡೀಫಾಲ್ಟ್ ಕ್ರಮ' },
  },
  mr: {
    any: 'कोणतेही',
    allCities: 'सर्व शहरे',
    allSkills: 'सर्व कौशल्ये',
    searchByCity: 'उपलब्ध जुळते पाहण्यासाठी शहर आणि कौशल्य द्वारा शोधा',
    showMatching: 'जुळणारे कामगार दाखवा',
    city: { kurnool: 'कुरनूल', bhiwani: 'भिवानी', delhi: 'दिल्ली', hyderabad: 'हैदराबाद', mumbai: 'मुंबई', pune: 'पुणे', bengaluru: 'बेंगळुरू', chennai: 'चेन्नई', kolkata: 'कोलकाता', gurugram: 'गुरुग्राम', noida: 'नोएडा', ghaziabad: 'गाझियाबाद', faridabad: 'फरीदाबाद', lucknow: 'लखनौ', kanpur: 'कानपूर', jaipur: 'जयपूर', ahmedabad: 'अहमदाबाद', surat: 'सुरत', vadodara: 'वडोदरा', indore: 'इंदूर', bhopal: 'भोपाल', nagpur: 'नागपूर', nashik: 'नाशिक', patna: 'पाटणा', ranchi: 'रांची', bhubaneswar: 'भुवनेश्वर', chandigarh: 'चंदीगड', amritsar: 'अमृतसर', ludhiana: 'लुधियाना', kochi: 'कोची', thiruvananthapuram: 'तिरुवनंतपुरम', vijayawada: 'विजयवाडा', visakhapatnam: 'विशाखापट्टणम', warangal: 'वारंगल', tirupati: 'तिरुपती', coimbatore: 'कोयंबतूर', madurai: 'मदुराई', dehradun: 'देहरादून', guwahati: 'गुवाहाटी' },
    skill: { cooking: 'स्वयंपाक', cleaning: 'साफसफाई', babysitting: 'मुलांची काळजी', eldercare: 'वृद्धांची काळजी', laundry: 'कपडे धुणे', utensils: 'भांडी धुणे', mopping: 'फरशी पुसणे', sweeping: 'झाडू मारणे', dusting: 'धूळ साफ करणे', bathroom_cleaning: 'बाथरूम साफसफाई', deep_cleaning: 'डीप क्लीनिंग', kitchen_helper: 'स्वयंपाकघर मदत', cooking_assistant: 'स्वयंपाक मदतनीस', nanny: 'नॅनी / आया', patient_care: 'रुग्णांची काळजी', ironing: 'इस्त्री', gardening: 'बागकाम', pet_care: 'पाळीव प्राण्यांची काळजी', live_in_help: 'घरात राहणारी मदत' },
    verification: { id: 'ID सत्यापित', police: 'पोलीस सत्यापित' },
    experience: { '': 'कोणताही अनुभव', 1: '1+ वर्षे', 2: '2+ वर्षे', 3: '3+ वर्षे', 5: '5+ वर्षे', 8: '8+ वर्षे' },
    salary: { '': 'कोणताही पगार', 5000: 'Rs 5,000 पर्यंत', 8000: 'Rs 8,000 पर्यंत', 10000: 'Rs 10,000 पर्यंत', 15000: 'Rs 15,000 पर्यंत', 20000: 'Rs 20,000 पर्यंत' },
    sort: { yes: 'सर्वाधिक विश्वास आधी', no: 'डीफॉल्ट क्रम' },
  },
  bn: {
    any: 'যেকোনো',
    allCities: 'সব শহর',
    allSkills: 'সব দক্ষতা',
    searchByCity: 'উপলব্ধ ম্যাচ দেখতে শহর এবং দক্ষতা দ্বারা সন্ধান করুন',
    showMatching: 'মেলে এমন কর্মী দেখান',
    city: { kurnool: 'কুর্নুল', bhiwani: 'ভিওয়ানি', delhi: 'দিল্লি', hyderabad: 'হায়দরাবাদ', mumbai: 'মুম্বাই', pune: 'পুনে', bengaluru: 'বেঙ্গালুরু', chennai: 'চেন্নাই', kolkata: 'কলকাতা', gurugram: 'গুরগাঁও', noida: 'নয়ডা', ghaziabad: 'গাজিয়াবাদ', faridabad: 'ফরিদাবাদ', lucknow: 'লখনউ', kanpur: 'কানপুর', jaipur: 'জয়পুর', ahmedabad: 'আহমেদাবাদ', surat: 'সুরাট', vadodara: 'ভাদোদরা', indore: 'ইন্দোর', bhopal: 'ভোপাল', nagpur: 'নাগপুর', nashik: 'নাশিক', patna: 'পাটনা', ranchi: 'রাঁচি', bhubaneswar: 'ভুবনেশ্বর', chandigarh: 'চণ্ডীগড়', amritsar: 'অমৃতসর', ludhiana: 'লুধিয়ানা', kochi: 'কোচি', thiruvananthapuram: 'তিরুবনন্তপুরম', vijayawada: 'বিজয়ওয়াড়া', visakhapatnam: 'বিশাখাপত্তনম', warangal: 'ওয়ারাঙ্গল', tirupati: 'তিরুপতি', coimbatore: 'কোয়েম্বাটোর', madurai: 'মাদুরাই', dehradun: 'দেরাদুন', guwahati: 'গুয়াহাটি' },
    skill: { cooking: 'রান্না', cleaning: 'পরিষ্কার', babysitting: 'শিশুর যত্ন', eldercare: 'বয়স্কদের যত্ন', laundry: 'কাপড় ধোয়া', utensils: 'বাসন ধোয়া', mopping: 'মেঝে মোছা', sweeping: 'ঝাড়ু দেওয়া', dusting: 'ধুলো পরিষ্কার', bathroom_cleaning: 'বাথরুম পরিষ্কার', deep_cleaning: 'গভীর পরিষ্কার', kitchen_helper: 'রান্নাঘরের সাহায্য', cooking_assistant: 'রান্নার সহকারী', nanny: 'ন্যানি / আয়া', patient_care: 'রোগীর যত্ন', ironing: 'ইস্ত্রি', gardening: 'বাগান করা', pet_care: 'পোষা প্রাণীর যত্ন', live_in_help: 'লাইভ-ইন সাহায্য' },
    verification: { id: 'ID যাচাই করা', police: 'পুলিশ যাচাই করা' },
    experience: { '': 'যেকোনো অভিজ্ঞতা', 1: '1+ বছর', 2: '2+ বছর', 3: '3+ বছর', 5: '5+ বছর', 8: '8+ বছর' },
    salary: { '': 'যেকোনো বেতন', 5000: 'Rs 5,000 পর্যন্ত', 8000: 'Rs 8,000 পর্যন্ত', 10000: 'Rs 10,000 পর্যন্ত', 15000: 'Rs 15,000 পর্যন্ত', 20000: 'Rs 20,000 পর্যন্ত' },
    sort: { yes: 'সর্বোচ্চ ভরসা আগে', no: 'ডিফল্ট ক্রম' },
  },
};

const CITY_CODES = [
  'kurnool',
  'bhiwani',
  'delhi',
  'hyderabad',
  'mumbai',
  'pune',
  'bengaluru',
  'chennai',
  'kolkata',
  'gurugram',
  'noida',
  'ghaziabad',
  'faridabad',
  'lucknow',
  'kanpur',
  'jaipur',
  'ahmedabad',
  'surat',
  'vadodara',
  'indore',
  'bhopal',
  'nagpur',
  'nashik',
  'patna',
  'ranchi',
  'bhubaneswar',
  'chandigarh',
  'amritsar',
  'ludhiana',
  'kochi',
  'thiruvananthapuram',
  'vijayawada',
  'visakhapatnam',
  'warangal',
  'tirupati',
  'coimbatore',
  'madurai',
  'dehradun',
  'guwahati',
];

const SKILL_CODES = [
  'cooking',
  'cleaning',
  'babysitting',
  'eldercare',
  'laundry',
  'utensils',
  'mopping',
  'sweeping',
  'dusting',
  'bathroom_cleaning',
  'deep_cleaning',
  'kitchen_helper',
  'cooking_assistant',
  'nanny',
  'patient_care',
  'ironing',
  'gardening',
  'pet_care',
  'live_in_help',
];
const EXPERIENCE_VALUES = ['', '1', '2', '3', '5', '8'];
const SALARY_VALUES = ['', '5000', '8000', '10000', '15000', '20000'];
const VERIFICATION_VALUES = ['', 'id', 'police'];
const SORT_VALUES = ['yes', 'no'];

const FIELD_LABELS = {
  en: {
    city: 'City / Area',
    skill: 'Skill',
    requiredSkill: 'Required skill',
    verification: 'Verification Level',
    experience: 'Min Experience (years)',
    salary: 'Max Salary',
    sort: 'Sort by Trust',
    search: 'Search workers',
  },
  hi: {
    city: 'शहर / क्षेत्र',
    skill: 'कौशल',
    requiredSkill: 'आवश्यक कौशल',
    verification: 'सत्यापन स्तर',
    experience: 'न्यूनतम अनुभव (साल)',
    salary: 'अधिकतम वेतन',
    sort: 'विश्वास के अनुसार क्रमबद्ध करें',
    search: 'काम खोजें',
  },
  te: {
    city: 'నగరం / ప్రాంతం',
    skill: 'నైపుణ్యం',
    requiredSkill: 'అవసరమైన నైపుణ్యం',
    verification: 'ధృవీకరణ స్థాయి',
    experience: 'కనీస అనుభవం (సంవత్సరాలు)',
    salary: 'గరిష్ట జీతం',
    sort: 'నమ్మకంతో వర్గీకరణ',
    search: 'నౌకరి శోధన',
  },
  kn: {
    city: 'ನಗರ / ಪ್ರದೇಶ',
    skill: 'ಕೌಶಲ್ಯ',
    requiredSkill: 'ಬೇಕಾದ ಕೌಶಲ್ಯ',
    verification: 'ಸत्यೀಕರಣ ಮಟ್ಟ',
    experience: 'ಕನಿಷ್ಠ ಅನುಭವ (ವರ್ಷಗಳು)',
    salary: 'ಗರಿಷ್ಠ ಸಂಬಳ',
    sort: 'ನಂಬಿಕೆಯಿಂದ ಕ್ರಮ ಬದ್ಧಿಸಿ',
    search: 'ಕೆಲಸ ಹುಡುಕಿ',
  },
  mr: {
    city: 'शहर / भाग',
    skill: 'कौशल्य',
    requiredSkill: 'आवश्यक कौशल्य',
    verification: 'सत्यापन पातळी',
    experience: 'किमान अनुभव (वर्ष)',
    salary: 'कमाल वेतन',
    sort: 'विश्वासानुसार क्रम',
    search: 'काम शोधा',
  },
  bn: {
    city: 'শহর / এলাকা',
    skill: 'দক্ষতা',
    requiredSkill: 'প্রয়োজনীয় দক্ষতা',
    verification: 'যাচাইকরণ স্তর',
    experience: 'ন্যূনতম অভিজ্ঞতা (বছর)',
    salary: 'সর্বোচ্চ বেতন',
    sort: 'বিশ্বাসের ক্রমে',
    search: 'কর্ম সন্ধান',
  },
};

function languageLabels(language) {
  return LABELS[language] || LABELS.en;
}

function languageFieldLabels(language) {
  return FIELD_LABELS[language] || FIELD_LABELS.en;
}

function option(value, label) {
  return { value, label };
}

export function getFilterOptions(language = 'en') {
  const labels = languageLabels(language);
  const fieldLabels = languageFieldLabels(language);

  return {
    labels,
    fieldLabels,
    cities: [option('', labels.allCities), ...CITY_CODES.map((code) => option(code, labels.city[code] || LABELS.en.city[code]))],
    skills: [option('', labels.allSkills), ...SKILL_CODES.map((code) => option(code, labels.skill[code] || LABELS.en.skill[code]))],
    verification: VERIFICATION_VALUES.map((value) => option(value, value ? labels.verification[value] : labels.any)),
    experience: EXPERIENCE_VALUES.map((value) => option(value, labels.experience[value] || LABELS.en.experience[value])),
    salary: SALARY_VALUES.map((value) => option(value, labels.salary[value] || LABELS.en.salary[value])),
    sortByTrust: SORT_VALUES.map((value) => option(value, labels.sort[value] || LABELS.en.sort[value])),
  };
}
